### ISSUE TITLE
Bad memory access on sqrt(2) mod 3.

### ISSUE THREAD

**Issue by fedelebron** [Magtheridon96/Square-Root-Modulo-N#1]
Consider `sqrt_mod_n(2, 3)`. On line 424 `roots` will be empty. We then try to access `roots[0]` and `roots[1]` on line 435. This will die.

**Comment by Magtheridon96** [comment]
> Consider `sqrt_mod_n(2, 3)`. On line 424 `roots` will be empty. We then try to access `roots[0]` and `roots[1]` on line 435. This will die.

@fedelebron 
I just went over the implementation, are you sure? From what I see, it should branch into the section on line 406 since n=3 will be prime, and Tonelli-Shanks will run and yield no roots, which is the expected behavior.

**Comment by fedelebron** [comment]
How odd. It seems to think 3 is not prime: https://repl.it/repls/PoliticalSnivelingParticles. Can you reproduce? What I've changed there (to make it compile on repl.it) is 8ll became int64_t{8}, and I fixed the printing routine (first function in the file). Everything else is untouched.

**Comment by fedelebron** [comment]
(If I remember correctly, Miller-Rabin should special case the instances where `n` is exactly one of the witnesses.)

**Comment by Magtheridon96** [comment]
@fedelebron Ah yes, you're correct, the bug is indeed in the Miller-Rabin implementation.
I do indeed need to have the witnesses as special cases. Will fix now! Thank you for catching this!

**Comment by Magtheridon96** [comment]
Alright, done. I also cleaned up the code and split it into a few files.
It should be a lot better now.
